// The react-app-env.d.ts file is a TypeScript declaration file in a React application.
// It is used to define global types and declarations for the entire application.
// It provides a central place to define custom types, interfaces, and global variables that are used throughout the project.
// This file is automatically generated when you create a new React app using Create React App (CRA) and is responsible for providing type definitions and ambient declarations for the React application.

/// <reference types="react-scripts" />